### ISSUE TITLE
FR: Stealthchop mode for Extruder for Quieter Operation

### ISSUE THREAD

**Issue by talldonkey** [matthewlloyd/Llama-Mini-Firmware#1]
FR is for overall end goal for a quieter printer 

Hypothesis:  Switching Extruder to Stealthchop will make it quieter, and hopefully doesn't have downsides.

The stock prusa mini firmware has the Extruder in spreadcycle mode.  I believe the X Y Z axis are already in stealthchop. 
There may be an theoretical opportunity to quiet the extruder down by switching the extruder to stealthchop.  This may require tweaks such as upping the extruder current a bit for reliable operation, if it doesn't work at stock current.

**Comment by matthewlloyd** [comment]
I won't have a chance to implement this personally but I'm happy to review any related pull requests. It would need to be made optional and adjustable via the settings menu, and tested to make sure the extruder doesn't skip even more steps than it already does.

**Comment by espr14** [comment]
`M569 S1 E` command should do the work.

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
