### ISSUE TITLE
Ability to name sheets

### ISSUE THREAD

**Issue by audiorazor** [matthewlloyd/Llama-Mini-Firmware#10]
First off, thank you for making this firmware.   Feels good to have control over my printer again.  

Do you think there is any way you could modify it so we can actually name the steel sheets?

**Comment by espr14** [comment]
This should come with original FW. Probably with Prusa XL release.

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
