### ISSUE TITLE
[BUG]<Mesh bed leveling  hangs the system>

### ISSUE THREAD

**Issue by Sorav1** [matthewlloyd/Llama-Mini-Firmware#11]
Sir, I have installed the latest version of your firmware but when I do mesh calibration from lcd the system hangs and I need to reset all the time. The issue is not there with original Prusa firmware.

**Comment by Sorav1** [comment]
https://youtu.be/JloiyZ9ovZA

**Comment by matthewlloyd** [comment]
Do you have skew coefficients enabled? That could potentially cause an out-of-bounds move. Just a hypothesis.

Please connect OctoPrint or some other G-Code terminal and see if there is any error output.

**Comment by Sorav1** [comment]
Hi greetings of the day.
I have tried keeping skew coefficients disabled/enabled but still the same issue.

**Comment by Sorav1** [comment]
Will connect the machine to pronteface and update you the results.

**Comment by matthewlloyd** [comment]
This is a month old, I'm going to close. If it's not fixed, please let me know.
