### ISSUE TITLE
Prusa disallows Llama Firmware

### ISSUE THREAD

**Issue by glidercat** [matthewlloyd/Llama-Mini-Firmware#12]
My recently purchased Mini+ does not allow Llama latest firmware update. Gives "firmware signature verification failed" "Error! #12606"
![IMG_20210816_184252](https://user-images.githubusercontent.com/89054874/129653006-c289c409-020e-4258-bf0b-da8b5231a780.jpg)

**Comment by matthewlloyd** [comment]
Please read https://github.com/matthewlloyd/Llama-Mini-Firmware#jailbreak-your-mini, or contact Prusa support for advice.
