### ISSUE TITLE
[QUESTION] Enabling SWD firmware debugging on Prusa mini/buddy board

### ISSUE THREAD

**Issue by matterenergy** [matthewlloyd/Llama-Mini-Firmware#13]
Hi Matthew,
Could you provide some details re: how you were able to do SWD debugging of the firmware on the buddy board (Prusa Mini) while developing the Llama-Mini-Firmware?

I'm able to debug a STM32F4-Discovery with an identical STM32F407VG MCU, but not the actual printer's buddy board. 
The board has the "appendix" removed. 
Using the SWD debug connector of the buddy board. 
nRST resets the board but does not halt it, not really allowing debugging or SWD firmware flashing. 

Prusa's site/forum do not appear helpful in this regard (SWD debugging).
Perhaps you can share some of your findings. 

Thank you

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
