### ISSUE TITLE
Custom extruder esteps greater than 500

### ISSUE THREAD

**Issue by buenso** [matthewlloyd/Llama-Mini-Firmware#14]
Hello @matthewlloyd 

After replacing the stock extruder with a pancake nema 17 (direct drive) , my esteps need to be set to 830

It seems that the max setting in the lcd menu is 500, and if I try to write to eeprom with M92 E830 and M500, it seems that nothing is saved?

I did create a gcode with these parameters, and saved to usb and then hit print, but every time i reboot the printer, it changes back to default value?

Is it possible to unlock the max value of 500 in the lcd menu?

**Comment by espr14** [comment]
Try the latest version but look into `Settings -> Experimental Settings`. You can set 1 to 1000.

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
