### ISSUE TITLE
[FEATURE REQUEST]<Enter comprehensive title>

### ISSUE THREAD

**Issue by SirDobrotivy** [matthewlloyd/Llama-Mini-Firmware#16]
Please create an option to resize the bed. I would like to enlarge the printable area.
Also, please specify that the bed is not heated. Unfortunately, the calibration is set to require heating.

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
