### ISSUE TITLE
[ENHANCEMENT] PID autotune

### ISSUE THREAD

**Issue by Fra085** [matthewlloyd/Llama-Mini-Firmware#17]
Printer type: MINI
Optional upgrades: PID autotune

It would be great if there was an easy way to manage PID autotune from the main menu.
At the moment it is only possible to perform it through gcode, or am I wrong?

Thanks a lot for your work, bringing us wonderful features.

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
