### ISSUE TITLE
Adjust Z Height Test in Wizard

### ISSUE THREAD

**Issue by dcs3473** [matthewlloyd/Llama-Mini-Firmware#2]
For those using the Mini Silicone Bed Level fix the default Z height may be to high.  This gives you a fail during the wizard setup process.  It proceeds and will continue to work fine but just seeing the error causes anxiety.  Im not sure exactly how you could adjust for this as some users may have different heights based on how they cut the silicone pieces.

**Comment by matthewlloyd** [comment]
This should be fixed by adjusting the height of the PINDA sensor as part of any hardware modifications made to the bed. Not much to do here on the firmware side.
