### ISSUE TITLE
Update to Prusa 4.3.4 firmware

### ISSUE THREAD

**Issue by s31teg** [matthewlloyd/Llama-Mini-Firmware#23]
Hello

I read you have stopped developing this. But would you keep developing as paid support?

**Comment by matthewlloyd** [comment]
That's correct - I no longer own a Prusa Mini so development isn't possible. Given that I would need to buy another one and cover the cost of my time, the price of me continuing development will likely exceed what anyone is willing to pay. That said, perhaps someone else in the community can continue the work.
