### ISSUE TITLE
Setting motor currents

### ISSUE THREAD

**Issue by SiegelDaniel** [matthewlloyd/Llama-Mini-Firmware#24]
Hello,

As I currently did a upgrade to the bear frame, the hardcoded motor current does not suffice anymore for Z. 

Where exactly can I edit the motor currents? M907 does not work.

thanks in advance!

**Comment by espr14** [comment]
Try `M906`.

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
