### ISSUE TITLE
[FEATURE REQUEST] Change Load/Unload feed length

### ISSUE THREAD

**Issue by dagognatt** [matthewlloyd/Llama-Mini-Firmware#25]
Having changed the bowden tube when upgrading extruder, I ended up with a bit shorter bowden tube than the original. This leads to the loading-procedure ramming filament into the hotend at full speed before starting the purge process. 

It would be nice to see an option to adjust the length of the fast-feeding part of loading filament. (If this firmware is still active)

**Comment by espr14** [comment]
Makes sense for direct drive mods as well.

**Comment by Eldenroot** [comment]
Good idea

**Comment by topchiyev** [comment]
Definitely a good idea!

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
