### ISSUE TITLE
[ENHANCEMENT]update based on 4.4.0 fw

### ISSUE THREAD

**Issue by g8toparadise** [matthewlloyd/Llama-Mini-Firmware#26]
**Printer type** - [MINI]
Since 4.4.0 FW is out will you update your llama? 
Unless you wait for a more stable release.

**Comment by threepoint2** [comment]
i understand matthew lloyd sold his prusa mini and stopped developing this firmware; unless someone forks it and updates it, this is now dead.

**Comment by espr14** [comment]
There are tons of changes. This will take some time.

**Comment by Eldenroot** [comment]
Maybe better to create a PR for Official firmware and implement.some.features to base.

**Comment by espr14** [comment]
4.4.0 is the biggest change for MINI (bigger BBF, WiFi etc.) since the beginning so it will need some proper testing.
PR #31

**Comment by espr14** [comment]
Happy Christmas, here's gift for you.
@matthewlloyd PR #31 is ready for review. It compiles but I haven't tested it yet.
Any volunteer to test OctoPrint screen and connection?
4.4.0 removes 102,000 lines while adds 770,000 lines of code.

**Comment by Eldenroot** [comment]
Great, thx

**Comment by espr14** [comment]
Here's the [FW_MINI_Llama_alpha_based_on_4.4.0.zip](https://github.com/matthewlloyd/Llama-Mini-Firmware/files/10298302/FW_MINI_Llama_alpha_based_on_4.4.0.zip)

**Comment by Eldenroot** [comment]
Thank you. What about other PRs  - are included or not?

**Comment by espr14** [comment]
Other PRs are not in this.

**Comment by prongato** [comment]
> Here's the [FW_MINI_Llama_alpha_based_on_4.4.0.zip](https://github.com/matthewlloyd/Llama-Mini-Firmware/files/10298302/FW_MINI_Llama_alpha_based_on_4.4.0.zip)
> Press knob during start to force loading. Bootloader >2.0.0 is needed. If you don't have it, install original FW 4.4.0 first.

I will help test it!  I have been so excited for this firmware because I am running a Mosquito and use the PID auto tune and like writing it to the EEPROM.  I will install it tomorrow.  What for format, etc do you want error reporting in?

**Comment by prongato** [comment]
> Here's the [FW_MINI_Llama_alpha_based_on_4.4.0.zip](https://github.com/matthewlloyd/Llama-Mini-Firmware/files/10298302/FW_MINI_Llama_alpha_based_on_4.4.0.zip)
> Press knob during start to force loading. Bootloader >2.0.0 is needed. If you don't have it, install original FW 4.4.0 first.

BTW, if you plan on possibly taking over or forking Llama, just tell me where to donate!  I fell in love with this version of firmware because I like to tinker with my Mini and the default firmware is locked down.

do you know if they’ve fixed the mesh level bug on 4.4.0 yet?

**Comment by prongato** [comment]
> Here's the [FW_MINI_Llama_alpha_based_on_4.4.0.zip](https://github.com/matthewlloyd/Llama-Mini-Firmware/files/10298302/FW_MINI_Llama_alpha_based_on_4.4.0.zip)
> Press knob during start to force loading. Bootloader >2.0.0 is needed. If you don't have it, install original FW 4.4.0 first.

- Tried to update the firmware on my Mini and get this error when rebooting [https://imgur.com/a/DkEHS01](url)

**Comment by espr14** [comment]
There's a plan to create indepentent repository. I'll let you know then. I think the bug is not fixed and won't be fixed soon because of XL release.

I'll look at the error. But it seems it won't be easy so it won't be soon.

**Comment by prongato** [comment]
> There's a plan to create indepentent repository. I'll let you know then. I think the bug is not fixed and won't be fixed soon because of XL release.
> 
> I'll look at the error. But it seems it won't be easy so it won't be soon.

Good to know.  I’m available and willing to help with any testing.  No hurry for me, I would prefer you port a latter release anyway because 4.4.0 has a mesh level bug I don’t think they’ve addressed yet.  

My biggest concern is a semi-consistent place to obtain unlocked firmware for my Mini so I have access to PID auto tunes, skew corrections, the ability to control the hotend fan percentage (I run a Slice Mosquito with a 25mm 5v fan on mine).   I appreciate any work you put into maintaining this firmware.  If you need donations or any support I can offer, please just let me know.

**Comment by espr14** [comment]
Meanwhile, there's version based on 4.3.4 https://github.com/matthewlloyd/Llama-Mini-Firmware/issues/19#issuecomment-1368281897.

**Comment by espr14** [comment]
Here's Llama's v4.4.01
https://github.com/Llama-FW/Llama-P32-FW/releases/tag/v4.4.01

**Comment by espr14** [comment]
Here are the latest releases.
@prongato You can donate here: https://www.patreon.com/espr14

**Comment by matthewlloyd** [comment]
Thanks for opening an issue. Unfortunately since I am no longer have time to maintain this project, I am closing all PRs and issues so that I can archive the repository.
