### ISSUE TITLE
M303 E-1 Bed Pid Fails

### ISSUE THREAD

**Issue by dcs3473** [matthewlloyd/Llama-Mini-Firmware#3]
When trying to do an M303 E-1 S? (any temp) fails with a message of...

Send: M303 E-1 S50 U1
Recv: PID Autotune failed! Temperature too high

Doesn't matter what temp you try, 50, 60, 70 they all fail.

**Comment by matthewlloyd** [comment]
This is caused by a bug in Prusa's version of Marlin: https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/798

The workaround is to use E-2 instead of E-1, e.g. `M303 E-2 S50 U1`.
