### ISSUE TITLE
[BUG]<Bootloop plz help>

### ISSUE THREAD

**Issue by qp0n4ik** [matthewlloyd/Llama-Mini-Firmware#6]
I have flashed the file from USB flashcard, and now I have constant bootloop, i have no idea how to reflash it in the DFU mode? could anyone make video of the process? do I need raspberry pi for that? I have original prusa mini 
I have very limited knowledge and don't understand "Flashing in DFU Mode"  instruction with python code, i could tip if anyone can help me, I really don't want to spent 100$ for new board.
P.S. I did break appendix before everything else and put black jumper on  BOOT0 and GND

**Comment by matthewlloyd** [comment]
Did you put the jumper back to its original position? That seems like the most likely explanation.

Unfortunately I have limited time to offer to support the hardware of Prusa Buddy boards and bootloader issues - I recommend contacting Prusa support directly for assistance with the appendix, jumpers, and flashing.

**Comment by qp0n4ik** [comment]
Why you closed the topic? No, I did not put a jumper on original place. Should I? Could you please give any guidance on how to make it work, please?
 I searched all over the internet and could not find any instructions

**Comment by matthewlloyd** [comment]
I just released v1.0.4 which fixes a small bug I just noticed, which could in theory cause a bootloop on some devices. I don't know whether this actually is the cause of your bootloop, but if you like you can give it a try once you're comfortable switching between firmwares.
