### ISSUE TITLE
[BUG]<First layer calibration >

### ISSUE THREAD

**Issue by Sorav1** [matthewlloyd/Llama-Mini-Firmware#9]
Hi this is Sorav here and I installed the firmware for testing. On doing calibration I went ahead with the repeat of first layer calibration ,on doing that the bed starts cooling down and it never starts heating .I need to reset from the LCD to do that again.

**Comment by Sorav1** [comment]
In the latest firmware the issue got resolved.

**Comment by matthewlloyd** [comment]
Glad to hear it, thanks for closing!
